#pragma config(Sensor, dgtl1,  gunPitch,       sensorDigitalOut)
#pragma config(Sensor, dgtl3,  shoot,          sensorDigitalOut)
#pragma config(Motor,  port2,           turret,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//minimum threshold for joystick input
const int threshold = 8;

void runTurret(float speed){
	motor[turret]  = speed;
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{
	while(1 == 1)
	{

		//turret pitch: move turret barrel up and down
		if (vexRT[Btn6D]) {
			SensorValue[gunPitch] = true;
		}
		if (vexRT[Btn6U]) {
			SensorValue[gunPitch] = false;
		}

		//turret shooting
		if (vexRT[Btn8R]) {
			SensorValue[shoot] = true;
		}
		else {
			SensorValue[shoot] = false;
		}

		//use right joystick to rotate turret
		float axis;

		//ignores controller movements that are under threshold to prevent controller drift
		if(abs(vexRT[Ch1]) > threshold)
		{
			axis = vexRT[Ch1] / 3;
		}
		else
		{
			axis = 0;
		}
		
		runTurret(axis);
	}
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
}
